apiVersion: v1
kind: Service
metadata:
  name: simple-api
  namespace: simple-api-namespace
  labels:
    app.kubernetes.io/name: simple-api
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: simple-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80